"""SEO and tool registry data extracted from app.py."""

TOOLS = {
    "device": {
        "zh": {
            "name": "设备信息工具",
            "title": "设备信息工具 - 浏览器 平台 时区 IP User-Agent | Tools24",
            "description": "查看当前设备和浏览器环境信息：毫秒级时间、IP、平台、语言、时区、浏览器、系统、屏幕、视口、CPU、内存、主题、触控和网络。",
            "keywords": "设备信息,浏览器信息,时区,IP,User-Agent,平台,屏幕分辨率,视口,CPU,内存",
            "intro": "查看当前浏览器与设备环境详情，包括毫秒级当前时间、IP、平台、语言、时区、浏览器、系统、屏幕、视口、CPU、内存、主题、触控能力与网络信息。",
            "features": ["毫秒级当前时间", "真实访客 IP（线上）", "平台 / 浏览器 / 系统", "屏幕 / 视口 / DPR", "CPU / 内存 / 主题 / 触控 / 网络"],
            "faq": [
                ("为什么本地显示 127.0.0.1？", "因为本地开发是浏览器直接访问本机服务，127.0.0.1 属正常现象。线上部署会优先读取 X-Forwarded-For。"),
                ("颜色主题显示的是什么？", "显示的是当前站内主题（dark / light），不是操作系统偏好主题。"),
            ],
        },
        "en": {
            "name": "Device Info",
            "title": "Device Info - Browser Platform Timezone IP User-Agent | Tools24",
            "description": "Inspect current device and browser info including millisecond clock, IP, platform, language, timezone, browser, OS, screen, viewport, CPU, memory, theme, touch and network.",
            "keywords": "device info,browser info,timezone,IP,user agent,platform,screen resolution,viewport,CPU,memory",
            "intro": "Inspect your current browser and device environment, including a millisecond clock, IP, platform, language, timezone, browser, OS, screen, viewport, CPU, memory, theme, touch capability and network information.",
            "features": ["Millisecond clock", "Real visitor IP in production", "Platform / browser / OS", "Screen / viewport / DPR", "CPU / memory / theme / touch / network"],
            "faq": [
                ("Why does local dev show 127.0.0.1?", "Because your browser is calling your local server directly. In production the app prefers X-Forwarded-For to show the real visitor IP."),
                ("What does the theme field show?", "It shows the current site theme (dark / light), not the OS preferred color scheme."),
            ],
        },
    },
    "color": {
        "zh": {
            "name": "颜色转换工具",
            "title": "颜色转换工具 - HEX RGB HSL HSV LAB OKLCH 在线互转与取色 | Tools24",
            "description": "在线颜色格式转换与取色工具，自动识别 HEX、RGB、HSL、HSV、HWB、CMYK、LAB、LCH、OKLab、OKLCH、XYZ 和 CSS 颜色名称。",
            "keywords": "颜色转换,HEX转RGB,RGB转HSL,HSV,CMYK,LAB,OKLCH,在线取色器,颜色吸管,CSS颜色",
            "intro": "输入任意一种常用颜色格式，即时得到其他格式结果并一键复制；也可使用系统颜色选择器、通道滑杆或浏览器吸管直接取色。",
            "features": ["自动识别常用颜色格式", "HEX ARGB / RGB / HSL / HSV / HWB", "CMYK / LAB / LCH / XYZ", "OKLab / OKLCH", "透明度与不透明度双向换算", "ARGB（AARRGGBB）输出", "系统选色与屏幕吸管", "浏览器本地处理"],
            "faq": [
                ("支持哪些输入格式？", "支持 HEX/ARGB（8 位使用 AARRGGBB）、RGB/RGBA、HSL/HSLA、HSV/HSB、HWB、CMYK、CIELAB/LCH、OKLab/OKLCH、CIE XYZ，以及浏览器支持的 CSS 颜色名称。"),
                ("为什么吸管按钮不可用？", "屏幕吸管依赖 EyeDropper API，目前主要在 Chromium 内核浏览器的安全页面中可用；其他浏览器仍可使用系统颜色选择器。"),
                ("颜色数据会上传吗？", "不会，识别、转换、选色和复制全部在当前浏览器本地完成。"),
            ],
        },
        "en": {
            "name": "Color Converter and Picker",
            "title": "Color Converter - HEX RGB HSL HSV LAB OKLCH Picker | Tools24",
            "description": "Convert and pick colors online with automatic detection for HEX, RGB, HSL, HSV, HWB, CMYK, LAB, LCH, OKLab, OKLCH, XYZ and CSS color names.",
            "keywords": "color converter,HEX to RGB,RGB to HSL,HSV,CMYK,LAB,OKLCH,color picker,eyedropper,CSS colors",
            "intro": "Enter any common color format to get every other representation instantly, or pick a color with the system picker, channel sliders or browser eyedropper.",
            "features": ["Automatic format detection", "HEX ARGB / RGB / HSL / HSV / HWB", "CMYK / LAB / LCH / XYZ", "OKLab / OKLCH", "Two-way opacity and transparency conversion", "ARGB (AARRGGBB) output", "System picker and screen eyedropper", "Local browser processing"],
            "faq": [
                ("Which input formats are supported?", "HEX/ARGB (8-digit values use AARRGGBB), RGB/RGBA, HSL/HSLA, HSV/HSB, HWB, CMYK, CIELAB/LCH, OKLab/OKLCH, CIE XYZ and CSS color names supported by your browser."),
                ("Why is the eyedropper button disabled?", "Screen sampling requires the EyeDropper API, currently available mainly in Chromium-based browsers on secure pages. The system color picker remains available elsewhere."),
                ("Are colors uploaded?", "No. Parsing, conversion, picking and copying all run locally in your browser."),
            ],
        },
    },
    "regex": {
        "zh": {
            "name": "正则表达式测试工具",
            "title": "正则表达式测试工具 - Regex 在线匹配替换 | Tools24",
            "description": "在线正则表达式测试工具，支持实时匹配高亮、JavaScript flags、捕获组、命名捕获组、替换预览和常用正则模板。",
            "keywords": "正则表达式测试,Regex测试,正则匹配,正则替换,捕获组,JavaScript RegExp,在线正则工具",
            "intro": "输入 JavaScript 正则表达式和测试文本，即时查看匹配高亮、匹配位置、捕获组及替换结果，并可从常用模板快速开始。",
            "features": ["实时匹配与高亮", "g / i / m / s / u flags", "普通与命名捕获组", "替换结果预览", "常用正则模板与本地历史"],
            "faq": [
                ("需要输入两侧的斜杠吗？", "不需要，只输入斜杠之间的表达式内容，flags 可通过右侧按钮选择。"),
                ("文本会上传服务器吗？", "不会，匹配和替换全部使用浏览器原生 JavaScript RegExp 在本地完成。"),
            ],
        },
        "en": {
            "name": "Regular Expression Tester",
            "title": "Regex Tester Online - Match Capture Replace | Tools24",
            "description": "Test JavaScript regular expressions online with live highlighting, flags, capture groups, named groups, replacement preview and common templates.",
            "keywords": "regex tester,regular expression tester,regex match,regex replace,capture groups,JavaScript RegExp,online regex tool",
            "intro": "Enter a JavaScript regular expression and test text to inspect live highlights, match positions, capture groups and replacement output, with common templates to get started.",
            "features": ["Live matching and highlighting", "g / i / m / s / u flags", "Numbered and named captures", "Replacement preview", "Common templates and local history"],
            "faq": [
                ("Should I enter the surrounding slashes?", "No. Enter only the pattern between the slashes and select flags with the controls on the right."),
                ("Is my text uploaded?", "No. Matching and replacement run locally with the browser's native JavaScript RegExp engine."),
            ],
        },
    },
    "http": {
        "zh": {
            "name": "HTTP 状态码与 Header 速查",
            "title": "HTTP 状态码与 Header 速查 - 请求头响应头 | Tools24",
            "description": "HTTP 状态码和 Header 在线速查，覆盖请求头、响应头、缓存、CORS、安全 Header，支持分类搜索和一键复制。",
            "keywords": "HTTP状态码,HTTP Header,请求头,响应头,Cache-Control,CORS,安全响应头,HTTP速查",
            "intro": "集中查询常用 HTTP 状态码及 Header 的含义和示例，包含请求、响应、缓存、CORS 与安全分类，点击即可复制。",
            "features": ["1xx 至 5xx 常用状态码", "请求头与响应头", "缓存控制 Header", "CORS 与安全 Header", "分类搜索与一键复制"],
            "faq": [
                ("401 和 403 有什么区别？", "401 表示缺少或无效的身份认证；403 表示服务器知道当前身份，但拒绝授予访问权限。"),
                ("no-cache 是否表示完全不缓存？", "不是。no-cache 允许存储响应，但每次复用前必须向服务器重新验证；完全禁止存储应使用 no-store。"),
            ],
        },
        "en": {
            "name": "HTTP Status and Header Reference",
            "title": "HTTP Status Codes and Headers Reference | Tools24",
            "description": "Search HTTP status codes and headers including requests, responses, caching, CORS and security headers, with examples and one-click copy.",
            "keywords": "HTTP status codes,HTTP headers,request headers,response headers,Cache-Control,CORS,security headers,HTTP reference",
            "intro": "Look up common HTTP status codes and header meanings with examples across request, response, caching, CORS and security categories, then copy with one click.",
            "features": ["Common 1xx through 5xx codes", "Request and response headers", "Caching headers", "CORS and security headers", "Category search and one-click copy"],
            "faq": [
                ("What is the difference between 401 and 403?", "401 means authentication is missing or invalid; 403 means the server knows the identity but refuses access."),
                ("Does no-cache disable caching?", "No. no-cache permits storage but requires revalidation before reuse. Use no-store to prevent storage entirely."),
            ],
        },
    },
    "format": {
        "zh": {
            "name": "代码格式化工具",
            "title": "代码格式化工具 - HTML CSS JS TS YAML XML Markdown | Tools24",
            "description": "在线代码格式化工具，基于 Prettier 支持 HTML、CSS、SCSS、JavaScript、TypeScript、JSON、YAML、XML、Markdown 等多种语言的美化。",
            "keywords": "代码格式化,HTML格式化,CSS格式化,JS格式化,TypeScript格式化,YAML格式化,XML格式化,Prettier,代码美化",
            "intro": "粘贴代码选择语言即可一键格式化，支持 HTML、CSS、SCSS、Less、JavaScript、TypeScript、JSON、YAML、XML、Markdown 等十种常见语言。",
            "features": ["HTML / CSS / SCSS / Less", "JavaScript / TypeScript", "JSON / YAML", "XML / Markdown", "Prettier 引擎，浏览器本地处理"],
            "faq": [
                ("格式化会上传代码吗？", "不会，基于 Prettier 在浏览器本地处理，代码不离开你的设备。"),
                ("支持哪些语言？", "HTML、CSS、SCSS、Less、JavaScript、TypeScript、JSON、YAML、XML、Markdown。"),
            ],
        },
        "en": {
            "name": "Code Formatter",
            "title": "Code Formatter - HTML CSS JS TS YAML XML Markdown | Tools24",
            "description": "Online code formatter powered by Prettier. Supports HTML, CSS, SCSS, Less, JavaScript, TypeScript, JSON, YAML, XML and Markdown.",
            "keywords": "code formatter,HTML formatter,CSS formatter,JS formatter,TypeScript formatter,YAML formatter,XML formatter,Prettier,beautify",
            "intro": "Paste code, pick a language, click Format. Supports HTML, CSS, SCSS, Less, JavaScript, TypeScript, JSON, YAML, XML and Markdown.",
            "features": ["HTML / CSS / SCSS / Less", "JavaScript / TypeScript", "JSON / YAML", "XML / Markdown", "Prettier engine, local browser processing"],
            "faq": [
                ("Is my code uploaded?", "No. Prettier runs locally in your browser; code never leaves your device."),
                ("Which languages are supported?", "HTML, CSS, SCSS, Less, JavaScript, TypeScript, JSON, YAML, XML and Markdown."),
            ],
        },
    },
    "json": {
        "zh": {
            "name": "JSON格式化校验工具",
            "title": "JSON格式化校验工具 - 在线 JSON Formatter / Viewer | Tools24",
            "description": "在线 JSON 格式化、压缩、校验和树形查看工具，支持快速检查 JSON 语法错误并复制格式化结果。",
            "keywords": "JSON格式化,JSON校验,JSON压缩,JSON Viewer,JSON Formatter,在线JSON工具",
            "intro": "粘贴 JSON 后即可格式化、压缩、校验语法并查看树形结构，适合接口调试、日志查看和配置文件整理。",
            "features": ["JSON 格式化与压缩", "语法错误提示", "树形层级查看", "JSON 转换为 YAML/XML/CSV/JS/Kotlin/Java/Go", "本地浏览器处理，不上传数据"],
            "faq": [
                ("JSON 格式化会上传数据吗？", "不会，Tools24 的 JSON 工具在浏览器本地运行。"),
                ("支持 JSON 压缩吗？", "支持，可以把格式化 JSON 压缩成单行。"),
            ],
        },
        "en": {
            "name": "JSON Formatter, Validator and Format Checker",
            "title": "JSON Format Checker Online - Formatter & Validator | Tools24",
            "description": "Paste or test JSON online to validate syntax, locate errors, format, compact and inspect nested data in a tree view.",
            "keywords": "JSON format checker,JSON formatter,JSON validator,test JSON online,JSON viewer,JSON compact",
            "intro": "Paste or test JSON online to check syntax, locate errors, format or compact the document, and inspect nested data in a tree view.",
            "features": ["Format and compact JSON", "Syntax validation", "Tree view", "Convert JSON to YAML/XML/CSV/JS/Kotlin/Java/Go", "Local browser processing"],
            "faq": [
                ("How can I test whether JSON is valid online?", "Paste the JSON and choose Format or Validate. The checker reports syntax errors with their line and column when available."),
                ("Does the JSON checker show the error location?", "Yes. Invalid JSON is reported with a line, column and nearby source context to help you fix it."),
                ("Is my JSON uploaded?", "No. Formatting and validation run locally in your browser."),
            ],
        },
    },
    "timestamp": {
        "zh": {
            "name": "时间戳转换工具",
            "title": "时间戳转换工具 - Unix Timestamp 在线转换 | Tools24",
            "description": "在线时间戳转换工具，支持秒/毫秒时间戳、日期时间、ISO 8601、UTC 和本地时间互转。",
            "keywords": "时间戳转换,Unix时间戳,毫秒时间戳,日期转换,ISO 8601,UTC时间",
            "intro": "输入任意常见时间格式，即可转换为秒级时间戳、毫秒时间戳、ISO、UTC、本地时间和相对时间。",
            "features": ["秒/毫秒时间戳互转", "ISO 8601 与 RFC 2822 输出", "UTC 和本地时间展示", "支持常见日期格式解析"],
            "faq": [
                ("秒时间戳和毫秒时间戳有什么区别？", "秒时间戳通常是 10 位，毫秒时间戳通常是 13 位。"),
                ("会根据本地时区转换吗？", "会，页面会显示当前浏览器所在时区。"),
            ],
        },
        "en": {
            "name": "Timestamp Converter",
            "title": "Timestamp Converter Online - Unix Time Converter | Tools24",
            "description": "Convert Unix timestamps, milliseconds, datetime, ISO 8601, UTC and local time online.",
            "keywords": "timestamp converter,Unix timestamp,milliseconds timestamp,ISO 8601,UTC time",
            "intro": "Convert common date strings into seconds, milliseconds, ISO, UTC, local time and relative time.",
            "features": ["Seconds and milliseconds", "ISO 8601 and RFC 2822 output", "UTC and local time", "Common date parsing"],
            "faq": [
                ("What is the difference between seconds and milliseconds?", "Second timestamps are usually 10 digits, while millisecond timestamps are usually 13 digits."),
                ("Does it use my local timezone?", "Yes. The page displays values based on your browser timezone."),
            ],
        },
    },
    "encoder": {
        "zh": {
            "name": "在线编码转换工具",
            "title": "在线编码转换工具 - URL编码 Base64 Base32 Base16 Unicode UTF-8 | Tools24",
            "description": "在线多类型编码转换工具，支持 URL编解码、Base64、Base32、Base16、Unicode转义、UTF-8字节、ASCII 七类互转。",
            "keywords": "URL编码,Base64,Base32,Base16,Unicode转义,UTF-8编码,ASCII转义,编码转换,字符编码",
            "intro": "选择编码类型，一键完成 URL、Base64、Base32、Base16、Unicode 转义、UTF-8 字节和 ASCII 之间的相互转换。",
            "features": ["URL 编解码", "Base64 / Base32 / Base16", "Unicode 转义 ↔ 文本", "UTF-8 字节 ↔ 文本", "ASCII 转义", "自动识别输入类型"],
            "faq": [
                ("支持哪些编码类型？", "支持 URL百分号编码、Base64、Base32、Base16、Unicode转义序列、UTF-8十六进制字节和 ASCII 编码。"),
                ("编码内容会上传服务器吗？", "不会，所有转换在浏览器本地完成。"),
            ],
        },
        "en": {
            "name": "Online Encoding Converter",
            "title": "Online Encoding Converter - URL Base64 Base32 Base16 Unicode UTF-8 | Tools24",
            "description": "Online multi-format encoding converter: URL encode/decode, Base64, Base32, Base16, Unicode escapes, UTF-8 hex bytes, and ASCII.",
            "keywords": "URL encoder,Base64,Base32,Base16,Unicode escape,UTF-8 hex,ASCII escape,encoding converter",
            "intro": "Choose an encoding type and convert between URL, Base64, Base32, Base16, Unicode escapes, UTF-8 hex bytes and ASCII.",
            "features": ["URL encode/decode", "Base64 / Base32 / Base16", "Unicode escapes ↔ text", "UTF-8 bytes ↔ text", "ASCII escaping", "Auto-detect input type"],
            "faq": [
                ("What encoding types are supported?", "URL percent-encoding, Base64, Base32, Base16, Unicode escape sequences, UTF-8 hex bytes, and ASCII encoding."),
                ("Is my data uploaded?", "No. All conversion happens locally in your browser."),
            ],
        },
    },
    "base64": {
        "zh": {
            "name": "Base64编码解码工具",
            "title": "Base64编码解码工具 - Base64 Encode Decode 在线转换 | Tools24",
            "description": "在线 Base64 编码解码工具，支持文本和文件转 Base64、Base64 还原下载文件。",
            "keywords": "Base64编码,Base64解码,Base64 Encode,Base64 Decode,文件转Base64",
            "intro": "支持文本 Base64 编码解码，也支持文件转 Base64 和 Base64 内容下载为文件。",
            "features": ["文本 Base64 编码", "文本 Base64 解码", "文件转 Base64", "Base64 还原文件"],
            "faq": [
                ("Base64 是加密吗？", "不是，Base64 是编码方式，不提供安全加密能力。"),
                ("支持文件转 Base64 吗？", "支持，可以在浏览器本地读取文件并生成 Base64。"),
            ],
        },
        "en": {
            "name": "Base64 Encoder and Decoder",
            "title": "Base64 Encoder and Decoder Online | Tools24",
            "description": "Encode and decode Base64 text online, convert files to Base64 and download decoded files.",
            "keywords": "Base64 encoder,Base64 decoder,Base64 encode,Base64 decode,file to Base64",
            "intro": "Encode or decode Base64 text, convert files to Base64 and restore decoded content as a download.",
            "features": ["Text Base64 encode", "Text Base64 decode", "File to Base64", "Decode Base64 to file"],
            "faq": [
                ("Is Base64 encryption?", "No. Base64 is an encoding format, not encryption."),
                ("Can it convert files to Base64?", "Yes. Files are read locally in your browser."),
            ],
        },
    },
    "diff": {
        "zh": {
            "name": "代码与文本对比工具",
            "title": "代码对比工具 - 在线 Text Diff / 字符差异比较 | Tools24",
            "description": "在线比较代码或文本的逐行和字符差异，支持文件导入、忽略空白与大小写，全部在浏览器本地处理。",
            "keywords": "代码对比,在线代码比较,文本对比,Diff工具,字符串差异,文件对比",
            "intro": "粘贴或导入两个版本的代码、配置、日志或普通文本，在浏览器本地查看逐行和字符级差异。",
            "features": ["代码和文本逐行对比", "字符级差异高亮", "忽略空白或大小写", "导入本地文本与代码文件", "浏览器本地处理"],
            "faq": [
                ("如何在线对比两段代码？", "粘贴或导入原始代码和修改后代码，选择比较选项后点击对比。"),
                ("支持字符串、配置文件和日志 Diff 吗？", "支持，可比较源代码、JSON、XML、YAML、SQL、配置、日志和普通文本。"),
                ("文本会上传服务器吗？", "不会，对比在浏览器本地完成。"),
            ],
        },
        "en": {
            "name": "Code Compare and Text Diff Tool",
            "title": "Code Compare Tool Online - Text & Code Diff | Tools24",
            "description": "Compare code or text online line by line. Highlight additions and deletions instantly with private browser-only processing and no uploads.",
            "keywords": "code compare tool,compare code online,code comparison,text diff,diff string,online diff tool",
            "intro": "Paste or import two versions of code, configuration, logs or plain text to compare line and character changes directly in your browser.",
            "features": ["Code and text comparison", "Line and character change highlights", "Ignore whitespace or letter case", "Import local text and code files", "Private browser-only processing"],
            "faq": [
                ("How do I compare two code snippets online?", "Paste or import the original and modified code, choose comparison options, and select Compare."),
                ("Can I diff strings, configuration files and logs?", "Yes. It compares any text-based content, including source code, JSON, XML, YAML, SQL, configs and logs."),
                ("Is my text uploaded?", "No. The comparison runs locally in your browser."),
            ],
        },
    },
    "android": {
        "zh": {
            "name": "Android 常用速查工具",
            "title": "Android 常用速查 - API ADB 权限 Intent Gradle 对照 | Tools24",
            "description": "Android 开发者常用速查：系统版本与 API Level、ADB 命令、透明度、dp/px、权限、Intent、Manifest 配置、资源限定符、生命周期和官方文档地址。",
            "keywords": "Android,API Level,安卓版本,ADB,权限,Intent,Manifest,资源限定符,Android文档,dp转px,屏幕密度,开发者工具",
            "intro": "Android 开发常用信息查询：API 版本、ADB 命令、透明度 Hex、dp/px、权限、Intent、Manifest、资源限定符、生命周期、Gradle 与官方文档地址。",
            "features": ["Android 版本 ↔ API Level 对照", "ADB 常用命令速查", "权限 / Intent / Manifest 配置查询", "资源限定符与生命周期对照", "Android 官方常用文档地址"],
            "faq": [
                ("Android API Level 最新是什么？", "截至 2026 年，Android 17 (Cinnamon Bun) 对应 API 37。"),
                ("dp 和 px 如何转换？", "px = dp × density。例如 mdpi (1x) 下 1dp = 1px，xxhdpi (3x) 下 1dp = 3px。"),
            ],
        },
        "en": {
            "name": "Android Quick Reference",
            "title": "Android Quick Reference - API ADB Permissions Intent Gradle | Tools24",
            "description": "Android developer quick reference: API levels, ADB commands, alpha values, dp/px, permissions, intents, Manifest config, resource qualifiers, lifecycle and official docs.",
            "keywords": "Android,API level,ADB,permissions,Intent,Manifest,resource qualifiers,Android docs,dp to px,screen density,developer tools",
            "intro": "Quick reference for Android developers: API levels, ADB commands, alpha hex values, dp/px, permissions, intents, Manifest, resource qualifiers, lifecycle, Gradle and official docs.",
            "features": ["Android version ↔ API level", "Common ADB commands", "Permissions / Intents / Manifest config", "Resource qualifiers and lifecycle", "Official Android docs links"],
            "faq": [
                ("What is the latest Android API level?", "As of 2026, Android 17 (Cinnamon Bun) corresponds to API 37."),
                ("How to convert dp to px?", "px = dp × density. For example, mdpi (1x): 1dp = 1px; xxhdpi (3x): 1dp = 3px."),
            ],
        },
    },
    "crypto": {
        "zh": {
            "name": "在线加解密工具",
            "title": "在线加解密工具 - AES RSA 对称非对称加密 | Tools24",
            "description": "在线加解密工具，支持 AES-GCM/CBC 对称加密和 RSA-OAEP 非对称加密，基于浏览器 Web Crypto API 本地处理，数据不上传。",
            "keywords": "AES加密,RSA加密,对称加密,非对称加密,在线加解密,Web Crypto,密钥生成",
            "intro": "支持对称加密（AES-GCM/CBC 密码派生）和非对称加密（RSA-OAEP 密钥对），所有操作在浏览器本地完成。",
            "features": ["AES-GCM / AES-CBC 对称加密", "PBKDF2 密码派生密钥", "RSA-OAEP 密钥对生成（2048/4096）", "PEM 格式密钥导出", "浏览器本地处理，数据不上传"],
            "faq": [
                ("加密数据会上传服务器吗？", "不会，加解密完全在浏览器本地使用 Web Crypto API 完成，密钥和明文不会离开本地。"),
                ("支持哪些加密算法？", "对称加密支持 AES-GCM 和 AES-CBC，非对称加密支持 RSA-OAEP，密钥长度可选 128/192/256 或 2048/4096 位。"),
            ],
        },
        "en": {
            "name": "Online Encryption Tool",
            "title": "Online Encryption Tool - AES RSA Symmetric Asymmetric | Tools24",
            "description": "Online encryption tool with AES-GCM/CBC symmetric and RSA-OAEP asymmetric encryption, powered by browser Web Crypto API — no data leaves your device.",
            "keywords": "AES encryption,RSA encryption,symmetric encryption,asymmetric encryption,online encryption,Web Crypto,key generation",
            "intro": "Symmetric encryption (AES-GCM/CBC with PBKDF2) and asymmetric encryption (RSA-OAEP with key pairs), all processed locally in your browser.",
            "features": ["AES-GCM / AES-CBC symmetric", "PBKDF2 key derivation", "RSA-OAEP key pair (2048/4096)", "PEM key export", "Local browser processing"],
            "faq": [
                ("Is my data sent to a server?", "No. All encryption/decryption uses the browser Web Crypto API locally. Keys and plaintext never leave your device."),
                ("Which algorithms are supported?", "Symmetric: AES-GCM and AES-CBC. Asymmetric: RSA-OAEP. Key lengths: 128/192/256 bit (AES) and 2048/4096 bit (RSA)."),
            ],
        },
    },
    "curl": {
        "zh": {
            "name": "在线 Curl 命令工具",
            "title": "在线 Curl 命令构建转换工具 - Curl Builder Converter | Tools24",
            "description": "在线 Curl 工具集：可视化构建 curl 命令、常用 curl 示例速查、curl 命令转 Python/JavaScript/Go/Java 代码。",
            "keywords": "curl命令,curl构建器,curl转代码,HTTP调试,API测试,curl示例",
            "intro": "可视化构建 curl 命令、浏览常用示例、一键转换为 Python/JS/Go/Java 代码，适合 API 调试和开发。",
            "features": ["可视化构建 curl 命令", "24 个常用 curl 示例速查", "curl → Python/JS/Go/Java 代码转换", "点击示例自动填充命令"],
            "faq": [
                ("curl 命令支持哪些转换语言？", "支持转换为 Python (requests)、JavaScript (fetch)、Go (net/http) 和 Java (OkHttp)。"),
                ("生成的 curl 命令可以直接运行吗？", "可以，复制后在终端粘贴即可运行。"),
            ],
        },
        "en": {
            "name": "Online Curl Command Tool",
            "title": "Online Curl Command Builder and Converter | Tools24",
            "description": "Online curl tool: visual command builder, common curl examples, and curl-to-code converter for Python/JavaScript/Go/Java.",
            "keywords": "curl command,curl builder,curl to code,HTTP debugging,API testing,curl examples",
            "intro": "Visually build curl commands, browse common patterns, and convert curl to Python/JS/Go/Java code for API development.",
            "features": ["Visual curl command builder", "24 common curl examples", "curl → Python/JS/Go/Java converter", "Click examples to autofill command"],
            "faq": [
                ("Which languages can curl be converted to?", "Python (requests), JavaScript (fetch), Go (net/http), and Java (OkHttp)."),
                ("Can I run the generated curl command?", "Yes, copy and paste into your terminal."),
            ],
        },
    },
    "flutter": {
        "zh": {
            "name": "Flutter 常用速查",
            "title": "Flutter 常用速查 - Widget CLI 状态管理 主题导航 | Tools24",
            "description": "Flutter 开发者常用速查，覆盖 Widget 组件、CLI 命令、常用 Packages、主题、导航、状态管理和响应式布局。",
            "keywords": "Flutter组件,Flutter Widget,Flutter CLI,Flutter状态管理,ThemeData,Flutter导航,Flutter速查",
            "intro": "集中查询 Flutter 常用 Widget、命令、Packages 和工程实践，并提供可复制示例与官方文档入口。",
            "features": ["60+ Widget 与代码示例", "Flutter CLI 命令", "常用 Packages 分类", "主题、导航与状态管理", "响应式布局与构建配置"],
            "faq": [("代码示例可以直接使用吗？", "示例用于快速理解常见写法，复制后请结合当前 Flutter 和依赖版本调整。"), ("内容是否来自官方文档？", "页面为便捷速查，并为各分类提供 Flutter 官方文档链接。")],
        },
        "en": {
            "name": "Flutter Quick Reference",
            "title": "Flutter Quick Reference - Widgets CLI State Theming Navigation | Tools24",
            "description": "Flutter developer reference covering widgets, CLI commands, popular packages, theming, navigation, state management and responsive layouts.",
            "keywords": "Flutter widgets,Flutter CLI,Flutter packages,Flutter state management,ThemeData,Flutter navigation,Flutter reference",
            "intro": "Browse common Flutter widgets, commands, packages and engineering patterns with copyable examples and links to official documentation.",
            "features": ["60+ widgets with examples", "Flutter CLI commands", "Popular package categories", "Theming, navigation and state management", "Responsive layout and build configuration"],
            "faq": [("Can I use the examples directly?", "The examples demonstrate common patterns. Adjust them for your current Flutter and dependency versions."), ("Is this official documentation?", "This is a quick reference with official Flutter documentation linked from each category.")],
        },
    },
    "ios": {
        "zh": {
            "name": "iOS 常用速查",
            "title": "iOS 常用速查 - SwiftUI UIKit Swift Xcode Info.plist | Tools24",
            "description": "iOS 开发者常用速查，覆盖 SwiftUI、UIKit、Swift 语法、Xcode 快捷键、Info.plist、HIG 和设备参数。",
            "keywords": "iOS开发,SwiftUI,UIKit,Swift语法,Xcode快捷键,Info.plist,HIG,iOS速查",
            "intro": "集中查询 iOS 开发中的 SwiftUI、UIKit、Swift、Xcode、权限配置、设计规范和设备参数。",
            "features": ["SwiftUI 视图与示例", "Swift 语法和 UIKit 类", "Xcode 快捷键", "Info.plist 权限配置", "HIG 与设备参数"],
            "faq": [("示例支持哪些 iOS 版本？", "不同 API 的最低版本不同，使用前请结合项目 Deployment Target 检查官方文档。"), ("是否包含官方资料？", "各分类均提供 Apple 或 Swift 官方文档入口。")],
        },
        "en": {
            "name": "iOS Quick Reference",
            "title": "iOS Quick Reference - SwiftUI UIKit Swift Xcode Info.plist | Tools24",
            "description": "iOS developer reference covering SwiftUI, UIKit, Swift syntax, Xcode shortcuts, Info.plist, HIG and device specifications.",
            "keywords": "iOS development,SwiftUI,UIKit,Swift syntax,Xcode shortcuts,Info.plist,HIG,iOS reference",
            "intro": "Browse SwiftUI, UIKit, Swift, Xcode, permission configuration, design guidance and device specifications in one place.",
            "features": ["SwiftUI views and examples", "Swift syntax and UIKit classes", "Xcode shortcuts", "Info.plist permission keys", "HIG and device specifications"],
            "faq": [("Which iOS versions are supported?", "Minimum versions differ by API. Check the linked official documentation against your deployment target."), ("Does it link to official sources?", "Each category links to Apple or Swift official documentation.")],
        },
    },
    "jwt": {
        "zh": {
            "name": "JWT 在线解析调试工具",
            "title": "JWT 在线解析调试工具 - 解码 验证 生成 | Tools24",
            "description": "在线解码、验证和生成 JWT，支持 HS256、HS384、HS512 和时间戳转换，全部在浏览器本地处理。",
            "keywords": "JWT解析,JWT解码,JWT验证,JWT生成,JSON Web Token,HS256,JWT调试",
            "intro": "粘贴 JWT 即可查看 Header、Payload 和签名信息，也可使用 HMAC 密钥验证或生成 Token。",
            "features": ["JWT Header 与 Payload 解码", "Claims 与时间戳解析", "HS256/HS384/HS512 验证", "JWT 生成", "浏览器本地处理，不上传 Token"],
            "faq": [("JWT 会上传服务器吗？", "不会，解析、验证和生成均使用浏览器原生能力在本地完成。"), ("解码是否代表签名可信？", "不代表。解码只读取内容，必须使用正确密钥完成签名验证后才能确认完整性。")],
        },
        "en": {
            "name": "JWT Decoder and Debugger",
            "title": "JWT Decoder and Debugger Online - Verify Generate | Tools24",
            "description": "Decode, verify and generate JWTs online with HS256, HS384, HS512 and timestamp inspection, entirely in your browser.",
            "keywords": "JWT decoder,JWT verifier,JWT generator,JSON Web Token,HS256,JWT debugger",
            "intro": "Inspect JWT headers, payloads and signatures, then verify or generate tokens using an HMAC secret locally in your browser.",
            "features": ["Decode JWT header and payload", "Inspect claims and timestamps", "HS256/HS384/HS512 verification", "JWT generation", "Local browser processing"],
            "faq": [("Are JWTs uploaded?", "No. Decoding, verification and generation run locally with browser APIs."), ("Does decoding prove a token is valid?", "No. Decoding only reads its contents; verify the signature with the correct secret to confirm integrity.")],
        },
    },
    "converter": {
        "zh": {
            "name": "在线文件转换工具",
            "title": "在线文件转换工具 - JSON CSV YAML XML PDF XLSX DOCX | Tools24",
            "description": "浏览器本地完成 JSON 与 CSV、YAML、XML 相互转换，并支持 TXT、HTML、Markdown、PDF、XLSX 和 DOCX，文件不上传服务器。",
            "keywords": "文件转换,JSON转CSV,YAML转JSON,XML转JSON,JSON转YAML,Markdown转PDF,CSV转XLSX,在线转换",
            "intro": "选择文件后仅显示可靠的目标格式，支持 JSON 与常见数据格式互转，以及文本、网页、表格和 DOCX 的轻量本地转换。",
            "features": ["JSON 与 CSV/YAML/XML 相互转换", "Markdown 转 HTML/TXT/PDF", "TXT/HTML/Markdown 互转", "CSV 与 XLSX 转换", "浏览器本地处理，不上传文件"],
            "faq": [("文件会上传服务器吗？", "不会，读取和转换均在当前浏览器完成。"), ("为什么不支持 PDF 转 DOCX？", "这类转换需要大型引擎且浏览器本地保真度较差，因此暂不提供。")],
        },
        "en": {
            "name": "Online File Converter",
            "title": "File Converter - JSON CSV YAML XML PDF XLSX DOCX | Tools24",
            "description": "Convert JSON to and from CSV, YAML and XML locally, plus TXT, HTML, Markdown, PDF, XLSX and DOCX formats, without uploading files.",
            "keywords": "file converter,JSON to CSV,YAML to JSON,XML to JSON,JSON to YAML,Markdown to PDF,CSV to XLSX,online converter",
            "intro": "Choose a file to see reliable outputs for JSON and common data formats, plus lightweight text, web, spreadsheet and DOCX conversion.",
            "features": ["JSON conversion with CSV/YAML/XML", "Markdown to HTML/TXT/PDF", "TXT/HTML/Markdown conversion", "CSV and XLSX conversion", "Local browser processing"],
            "faq": [("Are files uploaded?", "No. Reading and conversion happen in your current browser."), ("Why is PDF to DOCX unavailable?", "It requires a large engine and has poor browser-side fidelity, so it is intentionally excluded.")],
        },
    },
    "image": {
        "zh": {
            "name": "在线图片处理工具",
            "title": "在线图片处理工具 - 压缩 缩放 旋转 格式转换 | Tools24",
            "description": "在线图片压缩、缩放、旋转、翻转和 PNG/JPEG/WebP 格式转换，自动移除 EXIF/GPS 元数据，全部在浏览器本地完成。",
            "keywords": "图片压缩,图片缩放,图片旋转,图片格式转换,WebP转换,去除EXIF,在线图片工具",
            "intro": "上传图片后可调整尺寸、旋转、翻转、设置质量并转换为 PNG、JPEG 或 WebP。处理与导出完全在浏览器本地完成。",
            "features": ["图片压缩与质量调整", "缩放、旋转和翻转", "PNG/JPEG/WebP 格式转换", "移除 EXIF/GPS 元数据", "浏览器本地处理，不上传图片"],
            "faq": [
                ("图片会上传服务器吗？", "不会。读取、处理、预览和导出均由当前浏览器完成。"),
                ("为什么导出后拍摄信息消失了？", "Canvas 重新编码不会复制原图的 EXIF、GPS 等元数据，可用于保护隐私。"),
            ],
        },
        "en": {
            "name": "Online Image Tool",
            "title": "Image Tool - Compress Resize Rotate Convert Online | Tools24",
            "description": "Compress, resize, rotate, flip and convert images between PNG, JPEG and WebP locally in your browser, with metadata removed.",
            "keywords": "image compressor,image resize,image rotate,image converter,WebP converter,remove EXIF,online image tool",
            "intro": "Resize, rotate, flip, compress and convert images to PNG, JPEG or WebP. Processing and export happen entirely in your browser.",
            "features": ["Image compression and quality control", "Resize, rotate and flip", "PNG/JPEG/WebP conversion", "Remove EXIF/GPS metadata", "Local browser processing"],
            "faq": [
                ("Are images uploaded?", "No. Reading, processing, preview and export all happen in your current browser."),
                ("Why is camera information removed?", "Canvas re-encoding does not copy EXIF or GPS metadata, which helps protect privacy."),
            ],
        },
    },
    "qrcode": {
        "zh": {
            "name": "在线二维码生成解析工具",
            "title": "在线二维码生成解析工具 - QR Code Generator Parser | Tools24",
            "description": "在线二维码生成和解析工具，输入文本生成二维码图片下载，上传图片解析二维码内容，全部在浏览器本地完成。",
            "keywords": "二维码生成,二维码解析,QR Code,在线二维码,QR生成器",
            "intro": "输入文本或链接，自动生成可下载的二维码图片；上传或粘贴二维码图片即可解析内容。",
            "features": ["文本/链接生成二维码", "可调尺寸，PNG 下载", "图片上传/粘贴解析二维码", "浏览器本地处理，数据不上传"],
            "faq": [
                ("二维码内容会上传服务器吗？", "不会，生成和解析完全在浏览器本地完成。"),
                ("支持哪些输入类型？", "生成支持任意文本、URL、电话号码等；解析支持主流图片格式。"),
            ],
        },
        "en": {
            "name": "Online QR Code Generator and Parser",
            "title": "Online QR Code Generator and Parser | Tools24",
            "description": "Generate QR codes from text and parse QR codes from images — all processed locally in your browser.",
            "keywords": "QR code generator,QR code parser,online QR code,QR reader,QR creator",
            "intro": "Enter text to generate downloadable QR codes; upload or paste QR code images to decode their content.",
            "features": ["Text/URL to QR code", "Adjustable size, PNG download", "Image upload/paste parsing", "Local browser processing"],
            "faq": [
                ("Is my QR code data uploaded?", "No. Generation and parsing are done locally in your browser."),
                ("What formats are supported?", "Any text, URL, phone, etc. for generation; common image formats for parsing."),
            ],
        },
    },
    "markdown": {
        "zh": {
            "name": "Markdown 在线编辑预览工具",
            "title": "Markdown 在线编辑预览工具 - 实时预览/下载 HTML/DOC | Tools24",
            "description": "在线 Markdown 编辑器，支持实时预览、上传 .md 文件、下载为 HTML/DOC/Markdown 文件，全部在浏览器本地完成。",
            "keywords": "Markdown编辑器,Markdown预览,Markdown转HTML,在线Markdown,md文件",
            "intro": "左侧输入 Markdown，右侧实时预览渲染效果。支持上传 .md 文件，可下载为 HTML、DOC 或 Markdown 文件。",
            "features": ["实时 Markdown 预览", "上传 .md 文件编辑", "下载为 HTML / DOC / MD", "本地浏览器处理，不上传数据"],
            "faq": [
                ("Markdown 内容会上传吗？", "不会，所有编辑和渲染在浏览器本地完成。"),
                ("支持哪些导出格式？", "支持下载为 HTML 网页、DOC（Word 可打开）和原始 Markdown 文件。"),
            ],
        },
        "en": {
            "name": "Markdown Editor and Preview",
            "title": "Markdown Editor and Preview Online - Download HTML/DOC | Tools24",
            "description": "Online Markdown editor with live preview, .md file upload, download as HTML, DOC or Markdown file — all processed locally in your browser.",
            "keywords": "Markdown editor,Markdown preview,Markdown to HTML,online Markdown,md file",
            "intro": "Write Markdown on the left, see the rendered preview on the right. Upload .md files, download as HTML, DOC or Markdown.",
            "features": ["Live Markdown preview", "Upload .md files", "Download as HTML / DOC / MD", "Local browser processing"],
            "faq": [
                ("Is my Markdown uploaded?", "No. Editing and rendering happen locally in your browser."),
                ("What export formats are supported?", "Download as HTML, DOC (Word-compatible), or raw Markdown."),
            ],
        },
    },
    "fileinfo": {
        "zh": {
            "name": "MD5 哈希校验和文件信息工具",
            "title": "MD5 哈希校验工具 - 文件 MD5/SHA-256 在线验证 | Tools24",
            "description": "在线计算并校验文件 MD5、SHA-1 或 SHA-256，查看文件信息与媒体尺寸，全部在浏览器本地完成。",
            "keywords": "MD5哈希校验,文件MD5验证,SHA256校验,文件哈希,校验和,文件信息",
            "intro": "拖拽文件即可计算 MD5、SHA-1 和 SHA-256，与预期哈希进行匹配，并在本地查看文件及媒体信息。",
            "features": ["MD5/SHA-1/SHA-256 计算与校验", "文件大小和类型识别", "图片和音视频信息", "文件内容本地处理"],
            "faq": [
                ("文件会上传吗？", "不会，文件信息和哈希计算在浏览器本地完成。"),
                ("如何校验文件哈希？", "选择文件后，选择 MD5、SHA-1 或 SHA-256，再粘贴预期哈希即可查看是否匹配。"),
                ("MD5 适合用于密码安全吗？", "不适合。MD5 可用于兼容旧系统的文件完整性校验，但不应当用于密码存储或加密安全。"),
            ],
        },
        "en": {
            "name": "MD5 Hash Checker and File Info",
            "title": "MD5 Hash Checker Online - Verify File MD5 & SHA-256 | Tools24",
            "description": "Calculate and verify file MD5, SHA-1 or SHA-256 hashes online, inspect metadata and media dimensions, entirely in your browser.",
            "keywords": "MD5 hash checker,verify file MD5,SHA256 checker,file checksum,file hash,file info",
            "intro": "Drop a file to calculate its MD5, SHA-1 and SHA-256 hashes, compare an expected checksum, and inspect file or media metadata locally.",
            "features": ["Calculate and verify MD5/SHA-1/SHA-256", "File size and type", "Image/audio/video info", "Local file processing"],
            "faq": [
                ("Is my file uploaded?", "No. Files are processed locally in your browser."),
                ("How do I verify a file checksum?", "Choose the file, select MD5, SHA-1 or SHA-256, then paste the expected hash to see whether it matches."),
                ("Is MD5 suitable for password security?", "No. MD5 is useful for legacy file integrity checks, but it should not be used to store passwords or provide cryptographic security."),
            ],
        },
    },
    "terminal": {
        "zh": {
            "name": "终端常用命令速查",
            "title": "终端常用命令速查表 - Shell 命令参考 Linux 运维 | Tools24",
            "description": "终端常用命令速查表，覆盖文件操作、文本处理、进程管理、网络工具、系统信息、权限管理、压缩归档和 Shell 技巧，面向运维人员和终端用户。",
            "keywords": "终端命令,shell命令,Linux命令,运维命令,命令行速查,macOS命令,bash,zsh,终端常用命令",
            "intro": "面向运维人员和终端用户的常用 Shell 命令速查表，按类别分为文件操作、文本处理、进程管理、网络、系统、权限、压缩归档和 Shell 技巧八大类。",
            "features": ["文件操作命令", "文本处理命令", "进程管理命令", "网络工具命令", "系统信息命令", "权限管理命令", "压缩归档命令", "Shell 技巧"],
            "faq": [
                ("这些命令适用于哪些系统？", "大部分命令适用于 Linux 和 macOS，部分命令（如 apt）仅限特定发行版。"),
                ("如何查找特定命令？", "点击对应分类标签后使用搜索框，支持中英文关键词过滤。"),
            ],
        },
        "en": {
            "name": "Terminal Commands",
            "title": "Terminal Commands Cheat Sheet - Shell Reference Linux Ops | Tools24",
            "description": "Terminal commands quick reference covering file ops, text processing, process management, networking, system info, permissions, archives and shell tips for ops and terminal users.",
            "keywords": "terminal commands,shell commands,linux commands,ops commands,cli reference,bash,zsh,terminal cheat sheet",
            "intro": "A quick reference of common shell commands for ops and terminal users, organized into eight categories: file ops, text processing, process management, networking, system info, permissions, archives and shell tips.",
            "features": ["File operations", "Text processing", "Process management", "Network tools", "System info", "Permissions", "Archives", "Shell tips"],
            "faq": [
                ("Which systems do these commands apply to?", "Most commands work on Linux and macOS. Some (like apt) are distro-specific."),
                ("How do I find a specific command?", "Click a category tab then use the search box. Supports keyword filtering in both English and Chinese."),
            ],
        },
    },
    "ai": {
        "zh": {
            "name": "AI 指令速查",
            "title": "AI 指令速查 - Claude Code 与 Codex CLI 对照 | Tools24",
            "description": "Claude Code 与 Codex CLI 指令速查，涵盖快速开始、会话管理、自动化、权限安全、MCP、插件和代码审查，并提供常用功能对照。",
            "keywords": "AI CLI,Claude Code,Codex,AI编程助手,终端指令,MCP,代码审查,沙箱",
            "intro": "经过本地 CLI 帮助与官方资料核对的 Claude Code、Codex 指令参考，按实际任务分类并提供功能对照。",
            "features": ["Claude Code 分类指令", "Codex 分类指令", "会话与自动化", "权限与沙箱", "MCP 与插件", "功能对照"],
            "faq": [
                ("页面中的命令是否经过核对？", "命令基于当前安装版本的 CLI 帮助和官方资料核对，并在页面标注核对版本与日期。"),
                ("如何选择 Claude Code 或 Codex？", "可使用功能对照页按启动、会话、审批、沙箱、结构化输出和代码审查等任务比较。"),
            ],
        },
        "en": {
            "name": "AI CLI Commands",
            "title": "AI CLI Reference - Claude Code and Codex Comparison | Tools24",
            "description": "Verified Claude Code and Codex CLI reference covering quick start, sessions, automation, permissions, safety, MCP, plugins, code review, and task-by-task comparison.",
            "keywords": "AI CLI,Claude Code,Codex,AI coding assistant,terminal commands,MCP,code review,sandbox",
            "intro": "A Claude Code and Codex command reference verified against local CLI help and official materials, organized by real tasks with a side-by-side comparison.",
            "features": ["Claude Code commands", "Codex commands", "Sessions and automation", "Permissions and sandboxing", "MCP and plugins", "Feature comparison"],
            "faq": [
                ("Are the commands verified?", "Commands are checked against the installed CLI help and official materials, with the verified version and date shown on the page."),
                ("How should I choose between Claude Code and Codex?", "Use the comparison tab to compare startup, sessions, approvals, sandboxing, structured output, and code review workflows."),
            ],
        },
    },
    "translate": {
        "zh": {
            "name": "在线翻译工具",
            "title": "在线翻译工具 - 中英互译 单词音标 DeepSeek | Tools24",
            "description": "基于 DeepSeek 的智能翻译工具，自动检测中英文方向，短词显示 IPA 音标和词性标注，长文段落纯翻译，离开输入框自动触发。",
            "keywords": "在线翻译,中英翻译,单词音标,DeepSeek翻译,自动翻译,翻译工具",
            "intro": "输入任意文字即可智能翻译：中文自动译英文，其他语言自动译中文。短词附带 IPA 音标发音和词性，长文专注流畅翻译。离开输入框或停止输入 0.8 秒后自动翻译。",
            "features": ["中英文自动检测方向", "短词 IPA 音标 + 词性标注", "长文流畅翻译", "离开输入框自动翻译", "翻译历史记录"],
            "faq": [
                ("翻译引擎是什么？", "基于 DeepSeek Chat API，提供高质量中英互译。"),
                ("短词和长文有什么区别？", "≤5 个词的短文本会额外显示国际音标（IPA）、发音提示和词性；长文本仅输出流畅译文。"),
            ],
        },
        "en": {
            "name": "Online Translator",
            "title": "Online Translator - CN/EN with Phonetics DeepSeek | Tools24",
            "description": "DeepSeek-powered smart translator with auto language detection, IPA phonetics and POS tagging for words, pure translation for paragraphs. Translates on blur.",
            "keywords": "online translator,Chinese English translation,phonetics,DeepSeek translator,auto translate,IPA pronunciation",
            "intro": "Type anything to translate: Chinese → English or any language → Chinese. Short words get IPA phonetics and part-of-speech tags. Long text gets clean, fluent translation. Translates automatically when you leave the input or pause typing for 0.8s.",
            "features": ["Auto language detection", "IPA phonetics + POS for words", "Fluent long-text translation", "Translate on blur", "Translation history"],
            "faq": [
                ("What engine is used?", "DeepSeek Chat API, providing high-quality Chinese-English translation."),
                ("What's the difference for short vs long text?", "Short text (≤5 words) gets IPA pronunciation and POS tagging. Long text gets pure fluent translation."),
            ],
        },
    },
    "unitconvert": {
        "zh": {
            "name": "单位换算工具",
            "title": "单位与进制换算工具 - 二进制 十六进制 长度 温度 数据存储 | Tools24",
            "description": "在线单位换算工具，支持二、八、十、十六进制互转，并提供长度、面积、体积、质量、速度、温度、风力、数据存储等 16 类实时换算。",
            "keywords": "单位换算,进制换算,二进制转十进制,十六进制转十进制,长度换算,温度换算,数据存储换算,压力换算,燃油经济性,KB KiB",
            "intro": "在任意输入框输入数值，即时查看全部换算结果。首项支持二进制、八进制、十进制和十六进制任意互转，另有 16 类单位覆盖开发、生活、汽车与工程场景。",
            "features": ["二、八、十、十六进制互转", "任意精度整数与常用前缀", "长度、面积、体积、质量", "速度、温度、蒲福风力", "数据存储、时间、压力、能量、功率", "角度、流量、烹饪容量、燃油经济性", "浏览器本地计算与历史记录"],
            "faq": [
                ("二进制和十六进制支持多大的整数？", "使用浏览器 BigInt 任意精度整数计算，不受 JavaScript Number 安全整数范围限制；可输入负数及 0b、0o、0x 前缀。"),
                ("1 亩等于多少平方米？", "标准市亩为 2000/3 平方米，约 666.6667 平方米。"),
                ("盎司为什么出现在两个分类？", "常衡盎司 oz 是质量单位；美制和英制液量盎司 fl oz 是体积单位，二者不能直接互换。"),
                ("KB 和 KiB 有什么区别？", "KB 按十进制计算，1 KB = 1000 B；KiB 按二进制计算，1 KiB = 1024 B。"),
                ("PS 和 hp 都是马力吗？", "都是功率单位，但 PS 是公制马力，1 PS = 735.49875 W；hp 是机械马力，约 745.69987 W。"),
                ("US mpg 和 Imp mpg 为什么不同？", "它们分别使用美制加仑和英制加仑；英制加仑更大，所以相同油耗对应的 Imp mpg 数值更高。"),
                ("为什么时间换算没有月和年？", "月可能有 28–31 天，年也有平年和闰年，并非固定时长，因此这里只提供固定时长单位。"),
                ("风力等级能精确换成风速吗？", "不能。蒲福风级对应风速区间；输入风级时，本工具展示完整区间并使用区间中点估算其他速度单位。"),
                ("马赫换算是精确的吗？", "马赫会随温度和环境变化，本工具采用海平面 15°C 标准声速 340.29 m/s 作为常用近似。"),
            ],
        },
        "en": {
            "name": "Unit Converter",
            "title": "Unit and Number Base Converter - Binary Hex Length Temperature | Tools24",
            "description": "Convert binary, octal, decimal and hexadecimal integers plus 16 categories including length, temperature, data, pressure, energy and fuel economy.",
            "keywords": "unit converter,number base converter,binary to decimal,hex to decimal,length,temperature,data storage,pressure,energy,fuel economy,KB KiB",
            "intro": "Enter a value in any field to update every result instantly. The first category converts binary, octal, decimal and hexadecimal integers, followed by sixteen unit categories for development, daily life, cars and engineering.",
            "features": ["Binary, octal, decimal and hexadecimal", "Arbitrary-precision integers and common prefixes", "Length, area, volume and mass", "Speed, temperature and Beaufort wind", "Data, time, pressure, energy and power", "Angle, flow, cooking volume and fuel economy", "Local browser calculation and history"],
            "faq": [
                ("How large can binary or hexadecimal integers be?", "Conversion uses arbitrary-precision browser BigInt rather than JavaScript Number, with negative values and 0b, 0o and 0x prefixes supported."),
                ("How many square meters are in one mu?", "One standard Chinese mu is 2000/3 square meters, approximately 666.6667 m²."),
                ("Why do ounces appear in two categories?", "The avoirdupois ounce (oz) measures mass. US and Imperial fluid ounces (fl oz) measure volume and are separate units."),
                ("What is the difference between KB and KiB?", "KB is decimal: 1 KB = 1000 B. KiB is binary: 1 KiB = 1024 B."),
                ("Are PS and hp the same horsepower?", "Both measure power, but PS is metric horsepower at 735.49875 W while mechanical hp is about 745.69987 W."),
                ("Why are US mpg and Imperial mpg different?", "They use different gallon sizes. An Imperial gallon is larger, so the same consumption produces a higher Imperial mpg value."),
                ("Why are months and years omitted from time conversion?", "Months range from 28 to 31 days and years may be leap years, so they are not fixed durations."),
                ("Can Beaufort force be converted to an exact wind speed?", "No. Each Beaufort force represents a speed range. The tool shows that range and uses its midpoint only to estimate other speed units."),
                ("Is the Mach conversion exact?", "The speed of sound changes with conditions. This tool uses the common standard approximation of 340.29 m/s at sea level and 15°C."),
            ],
        },
    },
    "text": {
        "zh": {
            "name": "在线文本处理工具",
            "title": "在线文本处理工具 - 去重排序大小写多行转换 | Tools24",
            "description": "在线文本处理工具，支持去空行、去重、排序、大小写、空白整理，以及多行转 JSON、CSV、SQL IN 和带引号列表。",
            "keywords": "文本处理,文本去重,文本排序,删除空行,大小写转换,多行转JSON,SQL IN,文本统计",
            "intro": "在浏览器本地整理多行文本，可执行去重、排序、空白清理和大小写转换，也可转换为 JSON 数组、CSV、SQL IN 等开发常用格式。",
            "features": ["删除空行与行首尾空格", "多行去重与升降序", "大小写和连续空格处理", "多行转 JSON / CSV / SQL IN", "字符、行、单词和字节统计", "本地处理与历史记录"],
            "faq": [
                ("文本会上传服务器吗？", "不会，所有文本整理和格式转换都在浏览器本地完成。"),
                ("SQL IN 如何处理单引号？", "工具会把值中的单引号转义为两个单引号，生成可直接调整使用的字符串列表。"),
            ],
        },
        "en": {
            "name": "Online Text Processing Tool",
            "title": "Online Text Processing Tool - Dedupe Sort Case Convert | Tools24",
            "description": "Process text online with blank-line removal, deduplication, sorting, case conversion, whitespace cleanup and line conversion to JSON, CSV or SQL IN lists.",
            "keywords": "text processing,text dedupe,text sort,remove blank lines,case converter,lines to JSON,SQL IN,text statistics",
            "intro": "Clean multiline text locally in the browser with deduplication, sorting, whitespace cleanup and case conversion, or convert lines into JSON arrays, CSV and SQL IN lists.",
            "features": ["Remove blank lines and trim lines", "Deduplicate and sort lines", "Case and whitespace cleanup", "Lines to JSON / CSV / SQL IN", "Character, line, word and byte statistics", "Local processing and history"],
            "faq": [
                ("Is my text uploaded?", "No. All cleanup and conversion runs locally in your browser."),
                ("How are quotes handled for SQL IN?", "Single quotes inside values are escaped as two single quotes, producing a list you can safely adapt for SQL."),
            ],
        },
    },
    "git": {
        "zh": {
            "name": "Git 常用命令速查",
            "title": "Git 常用命令速查 - Git Cheat Sheet 远程地址替换 | Tools24",
            "description": "Git 常用命令速查表，覆盖基础操作、分支管理、撤销回退、远程管理、暂存日志、标签子模块和高级操作七大类。支持一键替换远程地址和分支名。",
            "keywords": "Git命令,Git Cheat Sheet,Git速查,git remote,git branch,分支管理,远程地址替换",
            "intro": "面向开发者的 Git 常用命令速查，七大类命令覆盖日常开发场景。底部两个实用工具：输入命令一键替换远程地址、一键替换分支名，方便切换仓库和分支命名规范变更。",
            "features": ["基础操作命令", "分支管理命令", "撤销回退命令", "远程管理命令", "暂存日志命令", "标签子模块命令", "高级操作命令", "一键替换远程地址", "一键替换分支名"],
            "faq": [
                ("替换远程地址怎么用？", "粘贴 git clone 或 git remote add 命令，输入新地址后点击替换，命令中的远程 URL 会自动替换。"),
                ("替换分支名怎么用？", "粘贴任意 git 命令，输入旧分支名和新分支名后点击替换，命令中所有匹配的分支名都会替换。"),
            ],
        },
        "en": {
            "name": "Git Commands",
            "title": "Git Cheat Sheet - Git Commands Reference Remote Branch | Tools24",
            "description": "Git commands quick reference covering basics, branching, undo, remote, stash/log, tags/submodules and advanced ops. Includes remote URL and branch name replacement tools.",
            "keywords": "Git commands,Git Cheat Sheet,git reference,git remote,git branch,branch management,remote URL replace",
            "intro": "A developer-focused Git commands quick reference across seven categories covering daily scenarios. Includes two utility tools: one-click remote URL replacement and branch name replacement for commands.",
            "features": ["Basic commands", "Branch management", "Undo & revert", "Remote management", "Stash & log", "Tags & submodules", "Advanced operations", "Remote URL replacement", "Branch name replacement"],
            "faq": [
                ("How to use remote URL replacement?", "Paste a git clone or git remote command, enter a new address, click Replace — the remote URL in the command will be updated automatically."),
                ("How to use branch name replacement?", "Paste any git command, enter old and new branch names, click Replace — all matching branch names in the command will be updated."),
            ],
        },
    },
    "tax": {
        "zh": {
            "name": "工资税收计算器",
            "title": "工资个税计算器 - 累计预扣 七级税阶明细 | Tools24",
            "description": "中国大陆工资个税估算，采用累计预扣法，展示1至12月预扣税额、七级超额累进税阶分档税额，并对比年终奖单独与合并计税。",
            "keywords": "个税计算器,工资税收计算器,个人所得税,年终奖计税,五险一金,税后工资,中国个税",
            "intro": "输入税前月薪、社保公积金比例和专项附加扣除，按累计预扣法估算全年个税，并查看逐月预扣与每个税阶的实际税额。",
            "features": ["累计预扣法", "1至12月预扣明细", "7级超额累进分档税额", "社保公积金估算", "年终奖单独/合并计税对比"],
            "faq": [
                ("年终奖单独计税和合并计税有什么区别？", "单独计税是将年终奖除以12后按月度税率表计算；合并计税是将年终奖并入当年综合所得按年累计税率计算。通常低收入合并更优，高收入单独更优，本工具自动对比推荐。"),
                ("计算结果准确吗？", "基于中国个人所得税法规定的7级超额累进税率计算，五险一金按默认比例估算。实际个税可能因各地社保基数上限、专项附加扣除细则等因素略有差异，仅供参考。"),
            ],
        },
        "en": {
            "name": "China Tax Calculator",
            "title": "China IIT Calculator - Cumulative Withholding & Tax Brackets | Tools24",
            "description": "China salary IIT estimate using cumulative withholding, with monthly withholding schedule, seven progressive bracket breakdown, and year-end bonus tax comparison.",
            "keywords": "China tax calculator,IIT calculator,personal income tax,year-end bonus tax,social insurance,net pay calculator",
            "intro": "Enter monthly salary, contribution rates, and special deductions to estimate IIT with cumulative withholding and inspect monthly and per-bracket tax details.",
            "features": ["Cumulative withholding", "12-month withholding schedule", "Seven-bracket tax breakdown", "Contribution estimate", "Year-end bonus comparison"],
            "faq": [
                ("Separate vs combined bonus taxation?", "Separate taxation divides the bonus by 12 and uses the monthly rate table. Combined taxation adds the bonus to annual comprehensive income using the annual table. Generally, combined favors lower incomes; this tool compares both automatically."),
                ("How accurate is the calculation?", "Based on China IIT law's 7-level progressive rates and default social insurance ratios. Actual tax may vary due to local social insurance caps, specific deduction rules, etc. For reference only."),
            ],
        },
    },
    "content": {
        "zh": {
            "name": "内容生成器",
            "title": "内容生成器 - 生成远程链接 纯文本托管 脚本分享 | Tools24",
            "description": "输入任意文本内容，生成一个远程链接，访问即可获取纯文本内容。适合远程脚本、配置文件托管和文本分享。",
            "keywords": "内容生成,远程链接,文本托管,脚本分享,在线文本,内容分享,pastebin",
            "intro": "输入任意文本内容，一键生成远程链接。访问该链接即可获取纯文本内容，适合托管远程脚本、配置文件或分享文本。",
            "features": ["一键生成远程链接", "纯文本直接访问", "支持脚本/配置/文本", "内容限制 1024 字符", "四种推荐命令一键复制"],
            "faq": [
                ("生成的内容会公开吗？", "链接本身不可猜测，但拥有链接的任何人都可以访问内容。请勿托管敏感信息。"),
                ("内容保存多久？", "内容默认保存 7 天，过期自动删除。"),
                ("内容大小有限制吗？", "单次内容限制 1,024 个字符。"),
            ],
        },
        "en": {
            "name": "Content Generator",
            "title": "Content Generator - Remote Link Plain Text Hosting Script Share | Tools24",
            "description": "Generate a remote link from any text content. Access it to get raw plain text — perfect for remote scripts, config hosting and text sharing.",
            "keywords": "content generator,remote link,text hosting,script sharing,online text,pastebin,content share",
            "intro": "Paste any text and generate a remote link. Visiting the link returns raw plain text — ideal for hosting remote scripts, configs or sharing text snippets.",
            "features": ["One-click remote link generation", "Raw plain text access", "Scripts / configs / text", "1,024 character limit", "4 recommended commands, click to copy"],
            "faq": [
                ("Is my content public?", "The link is unguessable, but anyone with the link can access the content. Do not host sensitive information."),
                ("How long is content kept?", "Content is stored for 7 days by default, then automatically deleted."),
                ("Is there a size limit?", "Single content is limited to 1,024 characters."),
            ],
        },
    },
    "mortgage": {
        "zh": {
            "name": "房贷计算器",
            "title": "房贷计算器 - 等额本息 等额本金 月供对比 | Tools24",
            "description": "在线房贷计算器，支持等额本息和等额本金两种还款方式，对比月供、利息总额和还款总额，实时计算一目了然。",
            "keywords": "房贷计算器,等额本息,等额本金,月供计算,贷款计算,利息计算,房贷对比",
            "intro": "输入贷款金额、年利率和贷款年限，同时展示等额本息和等额本金两种还款方式的月供、利息总额和还款总额，直观对比省多少利息。",
            "features": ["等额本息 / 等额本金双栏对比", "月供、利息总额、还款总额", "默认推荐值可修改", "实时计算与历史记录"],
            "faq": [
                ("等额本息和等额本金有什么区别？", "等额本息每月还款额固定，前期利息占比高，总利息更多；等额本金每月还款额递减，前期压力大但总利息更少。"),
                ("计算结果包含公积金贷款吗？", "本工具不区分贷款类型，仅根据金额和利率计算。如需混合贷，可分别计算后叠加。"),
            ],
        },
        "en": {
            "name": "Mortgage Calculator",
            "title": "Mortgage Calculator - Equal Installment vs Equal Principal | Tools24",
            "description": "Online mortgage calculator comparing equal installment and equal principal repayment methods, showing monthly payment, total interest and total payment side by side.",
            "keywords": "mortgage calculator,equal installment,equal principal,monthly payment,loan calculator,interest calculator",
            "intro": "Enter loan amount, annual rate and term to compare equal installment vs equal principal repayment methods side by side.",
            "features": ["Equal installment vs equal principal comparison", "Monthly payment, total interest, total payment", "Default values ready to tweak", "Real-time calculation and history"],
            "faq": [
                ("What is the difference between the two methods?", "Equal installment has fixed monthly payments with higher total interest. Equal principal has decreasing monthly payments with lower total interest."),
                ("Does this support combined loans?", "This calculator uses a single rate. For mixed loans, calculate separately and add the results."),
            ],
        },
    },
    "focus": {
        "zh": {
            "name": "专注力训练",
            "title": "舒尔特方格专注力训练 - 在线计时数字游戏 | Tools24",
            "description": "在线舒尔特方格专注力小游戏，提供 3×3 至 6×6 四档难度、顺序点击计时、错误统计、个人最佳和本地成绩记录。",
            "keywords": "舒尔特方格,专注力训练,注意力训练,视觉搜索,数字方格,舒尔特表,在线小游戏",
            "intro": "从 1 开始按顺序找出随机方格中的全部数字，在不同难度下练习视觉搜索和任务专注，并记录用时、错误次数与个人最佳。",
            "features": ["3×3 至 6×6 四档难度", "毫秒级计时与当前目标", "错误反馈和完成统计", "个人最佳与最近记录", "浏览器本地运行"],
            "faq": [
                ("舒尔特方格能提升专注力吗？", "它适合练习视觉搜索、顺序定位和对当前任务的持续投入，但不应理解为能全面提升智力或所有场景中的注意力。"),
                ("成绩会上传服务器吗？", "不会。游戏和成绩记录都在浏览器本地完成，最近记录仅保存在当前设备的 localStorage 中。"),
            ],
        },
        "en": {
            "name": "Focus Training",
            "title": "Schulte Grid Focus Training - Timed Number Game | Tools24",
            "description": "Play a timed Schulte Grid focus game with four levels from 3×3 to 6×6, mistake tracking, personal bests and local attempt history.",
            "keywords": "Schulte grid,focus training,attention game,visual search,number grid,timed brain game",
            "intro": "Find every shuffled number in order, starting from 1. Practice visual search and task focus across four levels while tracking time, mistakes and personal bests.",
            "features": ["Four levels from 3×3 to 6×6", "Millisecond timer and next target", "Mistake feedback and completion stats", "Personal bests and recent attempts", "Runs locally in your browser"],
            "faq": [
                ("Does a Schulte Grid improve attention?", "It can practice visual search, sequential scanning and staying engaged with the current task, but it should not be treated as proof of broader intelligence or attention gains."),
                ("Are my scores uploaded?", "No. The game and score tracking run locally. Recent attempts are stored only in this browser's localStorage."),
            ],
        },
    },
    "exchange": {
        "zh": {
            "name": "汇率计算器",
            "title": "汇率计算器 - 人民币美元日元韩元港币多币种换算 | Tools24",
            "description": "在线汇率计算器，支持百余种当前可用货币搜索选择，人民币、美元、欧元、日元、韩元、港币等常见币种推荐，并可同时换算和多结果对比。",
            "keywords": "汇率计算,货币换算,人民币兑美元,美元汇率,日元换算,韩元换算,港币换算,多币种对比",
            "intro": "输入金额，搜索选择任意支持的基准货币，并同时对比多个目标货币；人民币、美元、欧元、日元、韩元和港币等常用币种置顶推荐。",
            "features": ["百余种货币动态目录", "代码、名称和符号搜索", "常用币种置顶推荐", "多个换算结果同时对比", "参考汇率日期与本地历史"],
            "faq": [
                ("汇率是实时交易价格吗？", "不是。本工具使用央行和机构发布的每日参考汇率，适合估算，不代表银行、支付平台或外汇市场的实时成交价。"),
                ("为什么实际兑换金额不同？", "银行和支付平台通常会加入点差、手续费或自己的牌价，因此实际到账金额可能与参考换算结果不同。"),
            ],
        },
        "en": {
            "name": "Exchange Rate Calculator",
            "title": "Exchange Rate Calculator - Compare CNY USD JPY KRW HKD | Tools24",
            "description": "Search and select from over a hundred currently available currencies, with popular CNY, USD, EUR, JPY, KRW and HKD recommendations and side-by-side comparisons.",
            "keywords": "exchange rate calculator,currency converter,CNY to USD,USD exchange rate,JPY converter,KRW converter,HKD converter,multi currency comparison",
            "intro": "Enter an amount, search for any supported base currency, and compare multiple targets side by side, with popular currencies pinned first.",
            "features": ["Dynamic directory of 100+ currencies", "Search by code, name or symbol", "Popular currency recommendations", "Side-by-side comparisons", "Reference date and local history"],
            "faq": [
                ("Are these live trading rates?", "No. The tool uses daily reference rates published by central banks and institutions. They are useful for estimates, not live market execution."),
                ("Why is the amount from my bank different?", "Banks and payment providers may apply spreads, fees or their own quoted rates, so the final amount can differ from this reference conversion."),
            ],
        },
    },
    "area-search": {
        "zh": {
            "name": "地区搜索",
            "title": "地区搜索 - 中国省市地区编码查询 全球国家城市 | Tools24",
            "description": "在线中国省市区三级地区编码查询工具，支持全球国家城市搜索，GB/T 2260 标准编码，级联选择和名称搜索，一键复制完整路径。",
            "keywords": "地区搜索,中国省市区,地区编码,GB/T 2260,全球国家,城市搜索,区域代码,行政区域",
            "intro": "提供中国省市区三级地区编码查询（GB/T 2260 标准）以及全球国家城市搜索，支持级联选择、名称过滤和一键复制完整路径。",
            "features": ["中国省市区三级级联", "GB/T 2260 标准编码", "全球 250+ 国家城市", "输入即搜即时过滤", "完整路径一键复制"],
            "faq": [
                ("编码遵循什么标准？", "中国地区编码遵循 GB/T 2260 中华人民共和国行政区划代码标准，省份 2 位、城市 4 位、区县 6 位。"),
                ("数据会上传服务器吗？", "查询时的搜索请求会发送到服务器进行匹配，但不会记录或存储您的查询内容。"),
            ],
        },
        "en": {
            "name": "Area Search",
            "title": "Area Search - China Region Code Lookup Global Countries Cities | Tools24",
            "description": "Online China province/city/district code lookup with GB/T 2260 standards, global country and city search with cascading selection and one-click path copy.",
            "keywords": "area search,china region code,GB/T 2260,administrative division,global countries,city search,region lookup",
            "intro": "Look up China's three-level administrative region codes (GB/T 2260) and browse global countries and cities with cascading selection, name filtering and one-click path copy.",
            "features": ["3-level China cascading lookup", "GB/T 2260 standard codes", "250+ global countries and cities", "Type-to-filter on every level", "One-click full path copy"],
            "faq": [
                ("What standard do the codes follow?", "China region codes follow GB/T 2260 (Administrative Division Codes of the PRC): 2-digit province, 4-digit city, 6-digit district."),
                ("Is my search data uploaded?", "Search queries are sent to the server for matching but are not logged or stored."),
            ],
        },
    },
}

HOME_META = {
    "zh": {
        "name": "Tools24 在线开发者工具箱",
        "title": "Tools24 在线开发者工具箱 - JSON JWT 图片文件转换与开发速查",
        "description": "Tools24 提供 JSON 格式化、JWT 调试、图片与文件转换、编解码、加解密、二维码，以及 Android、Flutter、iOS 开发速查等免费在线工具。",
        "keywords": "在线工具,开发者工具,JSON格式化,编码转换,Base64,加解密,二维码生成,Markdown编辑器,Android速查,时间戳转换,文本对比,MD5校验",
        "intro": "Tools24 是面向开发者和日常办公的在线工具箱，提供三十多种编码、调试、文件处理、计算、效率和移动开发速查工具。",
    },
    "en": {
        "name": "Tools24 Online Developer Toolbox",
        "title": "Tools24 Developer Toolbox - JSON JWT Image File Tools and References",
        "description": "Free online tools for JSON, JWT, images, file conversion, codecs, encryption and QR codes, plus Android, Flutter and iOS developer references.",
        "keywords": "online tools,developer tools,JSON formatter,codec,Base64,encryption,QR code,Markdown editor,Android reference,timestamp converter,text diff,MD5 checker",
        "intro": "Tools24 provides over thirty browser-based tools for encoding, debugging, file processing, calculations, productivity and mobile development references.",
    },
}

TOOL_REGISTRY = {
    "device": {"order": 10, "icon": "console", "script": None, "global": None, "processing": "hybrid", "indexable": True},
    "json": {"order": 20, "icon": "json", "script": "/js/json-tool.js?v=20260715", "global": "JsonTool", "processing": "local", "indexable": True},
    "format": {"order": 30, "icon": "code", "script": "/js/format-tool.js?v=20260708", "global": "FormatTool", "processing": "local", "indexable": True},
    "timestamp": {"order": 40, "icon": "clock", "script": "/js/timestamp-tool.js?v=20260706", "global": "TimestampTool", "processing": "local", "indexable": True},
    "unitconvert": {"order": 50, "icon": "ruler", "script": "/js/unitconvert-tool.js?v=20260714a", "global": "UnitConvertTool", "processing": "local", "indexable": True},
    "color": {"order": 55, "icon": "palette", "script": "/js/color-tool.js?v=20260714", "global": "ColorTool", "processing": "local", "indexable": True},
    "regex": {"order": 60, "icon": "code", "script": "/js/regex-tool.js?v=20260710c", "global": "RegexTool", "processing": "local", "indexable": True},
    "http": {"order": 70, "icon": "console", "script": "/js/http-tool.js?v=20260710c", "global": "HttpTool", "processing": "local", "indexable": True},
    "encoder": {"order": 80, "icon": "code", "script": "/js/encoder-tool.js?v=20260706", "global": "EncoderTool", "processing": "local", "indexable": True},
    "crypto": {"order": 90, "icon": "shield", "script": "/js/crypto-tool.js?v=20260706", "global": "CryptoTool", "processing": "local", "indexable": True},
    "android": {"order": 100, "icon": "android", "script": "/js/android-tool.js?v=20260707", "global": "AndroidTool", "processing": "local", "indexable": True},
    "flutter": {"order": 110, "icon": "flutter", "script": "/js/flutter-tool.js?v=20260711", "global": "FlutterTool", "processing": "local", "indexable": True},
    "ios": {"order": 120, "icon": "ios", "script": "/js/ios-tool.js?v=20260711", "global": "IosTool", "processing": "local", "indexable": True},
    "translate": {"order": 130, "icon": "translate", "script": "/js/translate-tool.js?v=20260707", "global": "TranslateTool", "processing": "server", "indexable": True},
    "git": {"order": 140, "icon": "git", "script": "/js/git-tool.js?v=20260708", "global": "GitTool", "processing": "local", "indexable": True},
    "terminal": {"order": 150, "icon": "console", "script": "/js/terminal-tool.js?v=20260707", "global": "TerminalTool", "processing": "local", "indexable": True},
    "ai": {"order": 160, "icon": "ai", "script": "/js/ai-tool.js?v=20260710a", "global": "AiTool", "processing": "local", "indexable": True},
    "qrcode": {"order": 170, "icon": "qr", "script": "/js/qrcode-tool.js?v=20260706", "global": "QrcodeTool", "processing": "local", "indexable": True},
    "curl": {"order": 180, "icon": "terminal", "script": "/js/curl-tool.js?v=20260706", "global": "CurlTool", "processing": "local", "indexable": True},
    "base64": {"order": 190, "icon": "lock", "script": "/js/base64-tool.js?v=20260706", "global": "Base64Tool", "processing": "local", "indexable": True},
    "diff": {"order": 200, "icon": "diff", "script": "/js/diff-tool.js?v=20260715", "global": "DiffTool", "processing": "local", "indexable": True},
    "text": {"order": 210, "icon": "code", "script": "/js/text-tool.js?v=20260710a", "global": "TextTool", "processing": "local", "indexable": True},
    "tax": {"order": 220, "icon": "dollar", "script": "/js/tax-tool.js?v=20260710d", "global": "TaxTool", "processing": "local", "indexable": True},
    "mortgage": {"order": 230, "icon": "home", "script": "/js/mortgage-tool.js?v=20260710d", "global": "MortgageTool", "processing": "local", "indexable": True},
    "exchange": {"order": 232, "icon": "dollar", "script": "/js/exchange-tool.js", "global": "ExchangeTool", "processing": "hybrid", "indexable": True},
    "focus": {"order": 235, "icon": "target", "script": "/js/focus-tool.js", "global": "FocusTool", "processing": "local", "indexable": True},
    "image": {"order": 240, "icon": "file", "script": "/js/image-tool.js?v=20260711e", "global": "ImageTool", "processing": "local", "indexable": True},
    "converter": {"order": 250, "icon": "file", "script": "/js/converter-tool.js", "global": "ConverterTool", "processing": "local", "indexable": True},
    "fileinfo": {"order": 260, "icon": "file", "script": "/js/file-info-tool.js?v=20260706", "global": "FileInfoTool", "processing": "local", "indexable": True},
    "markdown": {"order": 270, "icon": "md", "script": "/js/md-tool.js?v=20260706", "global": "MdTool", "processing": "local", "indexable": True},
    "content": {"order": 280, "icon": "link", "script": "/js/content-tool.js?v=20260710b", "global": "ContentTool", "processing": "server", "indexable": True},
    "jwt": {"order": 290, "icon": "shield", "script": "/js/jwt-tool.js?v=20260711", "global": "JwtTool", "processing": "local", "indexable": True},
    "wishes": {"order": 300, "icon": "star", "script": "/js/wishes.js?v=20260706", "global": "WishTool", "processing": "server", "indexable": False, "hidden": True},
    "area-search": {"order": 310, "icon": "map-pin", "script": "/js/area-search-tool.js?v=20260712a", "global": "AreaSearchTool", "processing": "hybrid", "indexable": True},
}

TOOL_SUBPAGES = {
    "converter": {
        "markdown-to-pdf": {
            "zh": {"name": "Markdown 转 PDF 在线工具", "title": "Markdown 转 PDF 在线工具 | Tools24", "description": "浏览器本地将 Markdown 转为 PDF，提供预览、兼容性说明和示例。"},
            "en": {"name": "Markdown to PDF Online Tool", "title": "Markdown to PDF Online Tool | Tools24", "description": "Convert Markdown to PDF locally in your browser with preview, compatibility guidance and examples."},
        },
        "csv-to-xlsx": {
            "zh": {"name": "CSV 转 XLSX 在线工具", "title": "CSV 转 XLSX 在线工具 | Tools24", "description": "浏览器本地将 CSV 转换为 Excel XLSX 文件并预览表格内容。"},
            "en": {"name": "CSV to XLSX Online Converter", "title": "CSV to XLSX Online Converter | Tools24", "description": "Convert CSV to an Excel XLSX file and preview table content locally in your browser."},
        },
        "docx-to-html": {
            "zh": {"name": "DOCX 转 HTML 在线工具", "title": "DOCX 转 HTML 在线工具 | Tools24", "description": "浏览器本地提取 DOCX 标题、段落、列表和基础表格为 HTML。"},
            "en": {"name": "DOCX to HTML Online Converter", "title": "DOCX to HTML Online Converter | Tools24", "description": "Extract DOCX headings, paragraphs, lists and basic tables as HTML locally in your browser."},
        },
    },
    "flutter": {
        "widgets": {
            "zh": {"name": "Flutter Widgets 组件速查", "title": "Flutter Widgets 组件速查 | Tools24", "description": "Flutter Widget 组件目录、最低版本、完整示例和官方文档。"},
            "en": {"name": "Flutter Widgets Reference", "title": "Flutter Widgets Reference | Tools24", "description": "Flutter widget directory with minimum versions, complete examples and official documentation."},
        },
        "cli": {
            "zh": {"name": "Flutter CLI 命令速查", "title": "Flutter CLI 命令速查 | Tools24", "description": "Flutter 创建、构建、测试、分析和发布命令速查。"},
            "en": {"name": "Flutter CLI Command Reference", "title": "Flutter CLI Command Reference | Tools24", "description": "Flutter commands for project creation, builds, testing, analysis and releases."},
        },
        "packages": {
            "zh": {"name": "Flutter Packages 推荐", "title": "Flutter Packages 推荐 | Tools24", "description": "常用 Flutter Packages、维护状态、替代方案和 pub.dev 链接。"},
            "en": {"name": "Recommended Flutter Packages", "title": "Recommended Flutter Packages | Tools24", "description": "Popular Flutter packages with maintenance status, alternatives and pub.dev links."},
        },
    },
    "android": {
        "compose": {
            "zh": {"name": "Android Compose 组件速查", "title": "Android Compose 组件速查 | Tools24", "description": "Jetpack Compose 组件、Material 版本和代码示例。"},
            "en": {"name": "Android Compose Component Reference", "title": "Android Compose Component Reference | Tools24", "description": "Jetpack Compose components, Material versions and code examples."},
        },
        "adb": {
            "zh": {"name": "ADB 命令速查", "title": "ADB 命令速查 | Tools24", "description": "ADB 常用命令、输出示例、常见错误和排查建议。"},
            "en": {"name": "ADB Command Reference", "title": "ADB Command Reference | Tools24", "description": "Common ADB commands, output examples, errors and troubleshooting guidance."},
        },
        "permissions": {
            "zh": {
                "name": "Android Manifest 权限速查",
                "title": "Android 权限速查 - Manifest Permission 查询 | Tools24",
                "description": "查询 Android Manifest 权限、保护级别、最低 API 和第三方应用限制，覆盖危险、普通、特殊及系统权限。",
                "keywords": "Android权限,Manifest permission,android.permission.STATUS_BAR,权限保护级别,危险权限,系统权限",
                "intro": "搜索 Android Manifest 权限常量，查看用途、保护级别、API 版本和第三方应用限制，包括 STATUS_BAR 等系统权限。",
                "features": ["Manifest 权限常量搜索", "危险/普通/特殊/系统权限分类", "API 版本与平台限制", "STATUS_BAR 等系统权限说明", "Android 官方文档链接"],
                "faq": [
                    ("android.permission.STATUS_BAR 可以用于普通应用吗？", "不可以。该权限用于打开、关闭或禁用状态栏及其图标，Android 官方明确说明它不适用于第三方应用。"),
                    ("EXPAND_STATUS_BAR 和 STATUS_BAR 有什么区别？", "EXPAND_STATUS_BAR 是普通权限，可用于展开或收起状态栏；STATUS_BAR 是受限系统权限，普通第三方应用不能使用。"),
                ],
            },
            "en": {
                "name": "Android Manifest Permissions Reference",
                "title": "Android Permissions Reference - Manifest Permission Lookup | Tools24",
                "description": "Look up Android manifest permissions, protection levels, API requirements and restrictions for normal, dangerous, special and privileged permissions.",
                "keywords": "Android permissions,Manifest permission lookup,android.permission.STATUS_BAR,protection level,dangerous permission,privileged permission",
                "intro": "Search Android manifest permission constants and check their purpose, protection level, API requirements and third-party app restrictions, including STATUS_BAR.",
                "features": ["Manifest permission lookup", "Normal, dangerous, special and privileged levels", "API and platform restrictions", "STATUS_BAR and other system permissions", "Official Android documentation"],
                "faq": [
                    ("Can a third-party app use android.permission.STATUS_BAR?", "No. It controls opening, closing or disabling the status bar and its icons, and Android documents it as unavailable to third-party applications."),
                    ("What is the difference between EXPAND_STATUS_BAR and STATUS_BAR?", "EXPAND_STATUS_BAR is a normal permission for expanding or collapsing the status bar. STATUS_BAR is a restricted system permission unavailable to regular third-party apps."),
                ],
            },
        },
        "intent": {
            "zh": {"name": "Android Intent 速查", "title": "Android Intent 速查 | Tools24", "description": "Android 常用 Intent Action、权限和使用示例。"},
            "en": {"name": "Android Intent Reference", "title": "Android Intent Reference | Tools24", "description": "Common Android Intent actions, required permissions and usage examples."},
        },
    },
    "ios": {
        "swiftui": {
            "zh": {"name": "SwiftUI 组件速查", "title": "SwiftUI 组件速查 | Tools24", "description": "SwiftUI 组件、最低 iOS 版本和可复制示例。"},
            "en": {"name": "SwiftUI Component Reference", "title": "SwiftUI Component Reference | Tools24", "description": "SwiftUI components, minimum iOS versions and copyable examples."},
        },
        "uikit": {
            "zh": {"name": "UIKit 类速查", "title": "UIKit 类速查 | Tools24", "description": "UIKit 常用类、最低 iOS 版本和 Auto Layout 示例。"},
            "en": {"name": "UIKit Class Reference", "title": "UIKit Class Reference | Tools24", "description": "Common UIKit classes, minimum iOS versions and Auto Layout examples."},
        },
        "info-plist": {
            "zh": {"name": "Info.plist 权限配置速查", "title": "Info.plist 权限配置速查 | Tools24", "description": "Info.plist 权限 Key、审核说明和用户提示文案。"},
            "en": {"name": "Info.plist Privacy Key Reference", "title": "Info.plist Privacy Key Reference | Tools24", "description": "Info.plist privacy keys, review guidance and user-facing purpose strings."},
        },
        "xcode": {
            "zh": {"name": "Xcode 快捷键速查", "title": "Xcode 快捷键速查 | Tools24", "description": "Xcode 常用快捷键、场景和说明。"},
            "en": {"name": "Xcode Keyboard Shortcuts", "title": "Xcode Keyboard Shortcuts | Tools24", "description": "Common Xcode keyboard shortcuts with scenarios and explanations."},
        },
    },
}
